<a href="https://colab.research.google.com/github/SAIRAJU-ADDAGARLA/demo/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")
a=56776
print(a)

hello
56776


###ASSIGNMENT
Q1

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("addition",a + b)
print("subtraction",a-b)
print("multiplication",a*b)
print("division",a/b)

addition [5 7 9]
subtraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]


Q2

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(arr)
std_dev = np.std(arr)
mean,std_dev

(5.5, 2.8722813232690143)

Q3

In [ ]:

arr = np.arange(10, 51, 5)

arr


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Q4

In [ ]:
import numpy as np

arr = np.arange(10, 51, 5)[:8]
reshaped_arr = arr.reshape(2, 4)

reshaped_arr


array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

Q5

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_matrix = arr[1:, :2]


arr[arr > 4] = 0

sub_matrix, arr


(array([[4, 0],
        [0, 0]]),
 array([[1, 2, 3],
        [4, 0, 0],
        [0, 0, 0]]))

Q6

In [ ]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


addition = a + b
multiplication = a * b
division = a / b

addition, multiplication, division


(array([5, 7, 9]), array([ 4, 10, 18]), array([0.25, 0.4 , 0.5 ]))

Q7

In [ ]:
arr = np.random.randint(1, 100, size=(4, 4))

mean_column = np.mean(arr, axis=0)
max_value = np.max(arr)
sum_elements = np.sum(arr)

mean_column, max_value, sum_elements


(array([31.5, 74.5, 48.5, 30.5]), 94, 740)

Q8

In [ ]:

arr = np.array([1, 2, 3, 4])

result = (arr + 10) * 2

result


array([22, 24, 26, 28])

Q9

In [ ]:

arr = np.random.randint(1, 100, size=(3, 4, 5))

second_layer = arr[1]

extracted_part = arr[:, :2, -3:]

arr[arr % 3 == 0] = -1

second_layer, extracted_part, arr


(array([[-1, 65, -1, 40, -1],
        [-1, 55, -1, 58, 53],
        [89, 79, 22, -1, -1],
        [-1, 61, -1, 38, 55]]),
 array([[[65, -1, -1],
         [85, 52, -1]],
 
        [[-1, 40, -1],
         [-1, 58, 53]],
 
        [[50, 89, 14],
         [68,  5, 65]]]),
 array([[[79, -1, 65, -1, -1],
         [-1, 29, 85, 52, -1],
         [-1, -1, 19, 62, -1],
         [35, 11, 95, 14, 67]],
 
        [[-1, 65, -1, 40, -1],
         [-1, 55, -1, 58, 53],
         [89, 79, 22, -1, -1],
         [-1, 61, -1, 38, 55]],
 
        [[95, -1, 50, 89, 14],
         [38, -1, 68,  5, 65],
         [83, 26, 17, -1, -1],
         [61, 82, -1, 28, 91]]]))

Q10

In [ ]:

arr = np.random.randint(1, 20, size=(3, 3))
row_mean = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_mean
squared_arr = np.power(arr, 2)

top_3_indices = np.unravel_index(np.argsort(arr.ravel())[-3:], arr.shape)

print("normalized",normalized_arr)
print("square",squared_arr)
print("top 3 indices",top_3_indices)


normalized [[-4.66666667  5.33333333 -0.66666667]
 [ 5.          0.         -5.        ]
 [-6.         -1.          7.        ]]
square [[ 64 324 144]
 [256 121  36]
 [  4  49 225]]
top 3 indices (array([2, 1, 0]), array([2, 0, 1]))
